# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popkakati.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(746, 789)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 1000000))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ServoF = QtWidgets.QTextEdit(Dialog)
        self.ServoF.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ServoF.setObjectName("ServoF")
        self.verticalLayout_7.addWidget(self.ServoF)
        self.PortsliderF = QtWidgets.QSlider(Dialog)
        self.PortsliderF.setOrientation(QtCore.Qt.Horizontal)
        self.PortsliderF.setObjectName("PortsliderF")
        self.verticalLayout_7.addWidget(self.PortsliderF)
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setObjectName("comboBox_7")
        self.verticalLayout_7.addWidget(self.comboBox_7)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ServoE = QtWidgets.QTextEdit(Dialog)
        self.ServoE.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ServoE.setObjectName("ServoE")
        self.verticalLayout_6.addWidget(self.ServoE)
        self.PortsliderE = QtWidgets.QSlider(Dialog)
        self.PortsliderE.setOrientation(QtCore.Qt.Horizontal)
        self.PortsliderE.setObjectName("PortsliderE")
        self.verticalLayout_6.addWidget(self.PortsliderE)
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setObjectName("comboBox_6")
        self.verticalLayout_6.addWidget(self.comboBox_6)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ServoD = QtWidgets.QTextEdit(Dialog)
        self.ServoD.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ServoD.setObjectName("ServoD")
        self.verticalLayout_5.addWidget(self.ServoD)
        self.PortsliderD = QtWidgets.QSlider(Dialog)
        self.PortsliderD.setOrientation(QtCore.Qt.Horizontal)
        self.PortsliderD.setObjectName("PortsliderD")
        self.verticalLayout_5.addWidget(self.PortsliderD)
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_5.addWidget(self.comboBox_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ServoC = QtWidgets.QTextEdit(Dialog)
        self.ServoC.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ServoC.setObjectName("ServoC")
        self.verticalLayout_4.addWidget(self.ServoC)
        self.PortsliderC = QtWidgets.QSlider(Dialog)
        self.PortsliderC.setOrientation(QtCore.Qt.Horizontal)
        self.PortsliderC.setObjectName("PortsliderC")
        self.verticalLayout_4.addWidget(self.PortsliderC)
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setObjectName("comboBox_4")
        self.verticalLayout_4.addWidget(self.comboBox_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ServoB = QtWidgets.QTextEdit(Dialog)
        self.ServoB.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ServoB.setObjectName("ServoB")
        self.verticalLayout_3.addWidget(self.ServoB)
        self.PortsliderB = QtWidgets.QSlider(Dialog)
        self.PortsliderB.setOrientation(QtCore.Qt.Horizontal)
        self.PortsliderB.setObjectName("PortsliderB")
        self.verticalLayout_3.addWidget(self.PortsliderB)
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_3.addWidget(self.comboBox_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.Slider1 = QtWidgets.QVBoxLayout()
        self.Slider1.setObjectName("Slider1")
        self.ServoA = QtWidgets.QTextEdit(Dialog)
        self.ServoA.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ServoA.setBaseSize(QtCore.QSize(0, 0))
        self.ServoA.setObjectName("ServoA")
        self.Slider1.addWidget(self.ServoA)
        self.PortsliderA = QtWidgets.QSlider(Dialog)
        self.PortsliderA.setOrientation(QtCore.Qt.Horizontal)
        self.PortsliderA.setObjectName("PortsliderA")
        self.Slider1.addWidget(self.PortsliderA)
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setObjectName("comboBox_2")
        self.Slider1.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.Slider1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.PortCombobox = QtWidgets.QComboBox(Dialog)
        self.PortCombobox.setObjectName("PortCombobox")
        self.gridLayout.addWidget(self.PortCombobox, 0, 0, 1, 1)
        self.OPENPORT = QtWidgets.QPushButton(Dialog)
        self.OPENPORT.setObjectName("OPENPORT")
        self.gridLayout.addWidget(self.OPENPORT, 0, 1, 1, 1)
        self.CLOSEPORT = QtWidgets.QPushButton(Dialog)
        self.CLOSEPORT.setObjectName("CLOSEPORT")
        self.gridLayout.addWidget(self.CLOSEPORT, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.OPENFILEPORT = QtWidgets.QPushButton(Dialog)
        self.OPENFILEPORT.setObjectName("OPENFILEPORT")
        self.verticalLayout.addWidget(self.OPENFILEPORT)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ServoF.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Servo F</p></body></html>"))
        self.ServoE.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Servo E</p></body></html>"))
        self.ServoD.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Servo D</p></body></html>"))
        self.ServoC.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Servo C</p></body></html>"))
        self.ServoB.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Servo B</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ServoA.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Servo A</p></body></html>"))
        self.OPENPORT.setText(_translate("Dialog", "Open"))
        self.CLOSEPORT.setText(_translate("Dialog", "Close"))
        self.OPENFILEPORT.setText(_translate("Dialog", "OPEN FILE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
